# Template for node see:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml
# Coverage see:
# https://gist.github.com/rishitells/3c4536131819cff4eba2c8ab5bbb4570

image: node:18

stages:
  - test

javascript:
  stage: test
  script:
    - npm install
    - npm run build # we use ts-jest, no need for compilation but we get errors here
    - npm test
  artifacts:
    reports:
      junit:
        - junit.xml